USE contextsql;

INSERT IGNORE INTO business_glossary (term, definition, sql_snippet, tables_used) VALUES
('valid order',
 'An order that is not cancelled or returned. Status values are inconsistent, so compare lowercase and treat canceled/cancelled as the same.',
 "LOWER(o.status) NOT IN ('cancelled','canceled','returned')",
 'orders'),
('revenue',
 'Sum of line totals after discount, for valid orders only.',
 "SUM(oi.quantity * oi.unit_price * (1 - COALESCE(oi.discount_pct,0)/100))",
 'order_items, orders'),
('gross margin',
 'Revenue minus cost of goods sold (quantity * product cost_price), valid orders only.',
 "SUM(oi.quantity * oi.unit_price * (1 - COALESCE(oi.discount_pct,0)/100)) - SUM(oi.quantity * p.cost_price)",
 'order_items, products, orders'),
('average order value',
 'Revenue divided by the number of distinct valid orders.',
 "SUM(oi.quantity * oi.unit_price * (1 - COALESCE(oi.discount_pct,0)/100)) / COUNT(DISTINCT o.order_id)",
 'order_items, orders'),
('active customer',
 'A customer with at least one valid order in the last 90 days.',
 "o.order_date >= DATE_SUB(CURDATE(), INTERVAL 90 DAY) AND LOWER(o.status) NOT IN ('cancelled','canceled','returned')",
 'customers, orders'),
('churned customer',
 'A customer who has ordered before but has no valid order in the last 180 days.',
 "MAX(o.order_date) < DATE_SUB(CURDATE(), INTERVAL 180 DAY)",
 'customers, orders'),
('return rate',
 'Returned orders divided by all orders.',
 "SUM(LOWER(o.status) = 'returned') / COUNT(*)",
 'orders'),
('unpaid order',
 'A valid order with no payment row.',
 "NOT EXISTS (SELECT 1 FROM payments pay WHERE pay.order_id = o.order_id)",
 'orders, payments');
